$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_model_housing_ric
display_name: Entrenamiento de Modelo Lasso
version: 1
type: command
inputs:
  input_data: 
    type: uri_folder
  alpha:
    type: number
    default: 0.01
outputs:
  model_output:
    type: mlflow_model
  output_data:
    type: uri_folder
code: ./src/train-model/
environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
command: >-
  python train-model.py
  --input_data ${{inputs.input_data}}
  --alpha ${{inputs.alpha}}
  --model_output ${{outputs.model_output}}
  --output_data ${{outputs.output_data}}
