name: sklearn-azure-ai-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - scikit-learn
  - pandas
  - numpy
  - matplotlib
  - pip:
    - azure-ai-ml
    - azure-identity
    - mlflow
    - mltable
    - jsonschema
    - pathlib
    - pyspark
